### ISSUE TITLE
Coco datasets

### ISSUE THREAD

**Issue by alceubissoto** [Faruk-Ahmed/syst-gen#2]
Greetings!
First, thank you for sharing the code of your work! :)

I would like to ask you if the provided samples to COCO datasets (both color and places) comprehend the full set or just a subset of the data used in the paper's experiments. In case they are not complete, is it possible for you to share them?  

Thanks!

**Comment by Faruk-Ahmed** [comment]
Hello, the provided datasets (at the Dropbox link) are complete. I've described them as being a "sample" because running the data_maker would result in different images every time due to random elements in the dataset generation process.
