### ISSUE TITLE
Background leakage into foreground

### ISSUE THREAD

**Issue by PedroRASB** [Faruk-Ahmed/syst-gen#4]
Dear Dr. Ahmed,

I am working with your dataset, COCO_Places, and I believe that I have found an undesired behavior in the dataset creation code (coco/data/data_makers/coco_places.py). When you resize the COCO segmentation masks, you use the line "resized_mask = resize(mask, (64, 64), anti_aliasing=True)" or "resized_mask = resize(mask, (64, 64))". Both commands use bi-linear interpolation by default (https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.resize). Thus, resized_mask are not binary.

Accordingly, we have a small leakage of the Places' backgrounds into the COCO's foregrounds after the command “new_im = resized_place*(1-resized_mask) + resized_image*resized_mask”. Indeed, if you crop and compare just the foreground region in the iid, ood and sg test datasets, you will see that the foregrounds are not identical across the three partitions. I have corrected this behavior by substituting "resized_mask = resize(mask, (64, 64))" and "resize(mask, (64, 64), anti_aliasing=True)" by "resized_mask = resize(mask, (64, 64), anti_aliasing=False, order=0)". The new command uses nearest neighbor interpolation, ensuring that the result is binary. Thus, it prevents the leakage. 
I hope this comment will help. Thank you for your code and congratulations for your great work.

Best regards,

Pedro Bassi
PhD Student, University of Bologna, Italy

**Comment by Faruk-Ahmed** [comment]
Hey Pedro, I believe you might be right, nice catch! For the particular purpose in this paper, it probably won't change much for key results and takeaways, but if such a dataset is being used for experiments requiring zero leakage (e.g. segment foreground from background) then it could become relevant. If you use the NN mask in your own experiments, you might have to rerun baselines.
